### ISSUE TITLE
Static Linking

### ISSUE THREAD

**Issue by webfolderio** [Kray-G/kinx#98]
Hi,

Is it possible to link kinx as a static library and executable?

Thanks

**Comment by Kray-G** [comment]
You can link statically with kinx.obj which is a source of kinx.dll, but unfortunately it is not currently available to link with necessary modules full set because of its architecture design.
To resolve it, there are 2 main things I have to care about.

First, for example, kxsystem.dll and some modules will be automatically loaded at start-up.

Second one is many library is written and provided in kinx and it is expected to be into the library folder of kinx.

The possible solution that I thing is to link kinx.obj statically or dynamically use of kinx.dll. And then, you can include necessary dlls and all necessary libraries into your package.

I am sorry, if this is not your expected.

But thanks for the question!
