### ISSUE TITLE
Printing Non-ASCII

### ISSUE THREAD

**Issue by webfolderio** [Kray-G/kinx#99]
Hi,

kinx repl doesn't print non-ascii chars (Turkish), try to execute `System.println('çÇşŞiİğĞüÜıI');` with kinx repl.
I created a simple hello.knx file and it still doesn't print Turkish letters.

Thanks

**Comment by Kray-G** [comment]
Thanks for your report!
I am not familiar with Turkish but I will try to investigate it.

Please wait for a little while.

**Comment by Kray-G** [comment]
Here is my investigation result.

I am sorry I have a question.
What operating system do you use?
It is Windows because it is no problem for Linux, right?

1. On Linux

If the terminal is set by UTF-8 encoding, I don't find any problem.

```
~/github/kinx$ cat turkish.kx
System.println('çÇşŞiİğĞüÜıI');

~/github/kinx$ ./kinx turkish.kx
çÇşŞiİğĞüÜıI
~/github/kinx$
```

Repl is also okay.
I don't have any problem.

2. On Windows

I saw the Repl was not okay.
Maybe it is encoding issue.
Repl's standard input does always expect ACP.
I will do more investigation and try to fix it.

For the standard output, by default, converting to ACP(CP_ACP) from utf8 will be done when displayed.
Therefore the setting of the terminal's code page should be suited to the encoding to be displayed.
But I didn't succeed to set the code page for Turkish in my desktop, and I don't know what is the cause yet.

As an alternative solution, windows terminal of command line can be set to UTF8.
`kinx.exe` has an option of `-u` not to convert to ACP and kinx.exe will deal with the string of a utf-8 as is.
Here is my current suggestion now, if you can.

```
C:> chcp 65001
Active code page: 65001

C:> type turkish.kx
System.println('çÇşŞiİğĞüÜıI');

C:> kinx.exe -u turkish.kx
çÇşŞiİğĞüÜıI
```

I will report it to you again if I found a root cause of this.

Thanks in advance.

**Comment by Kray-G** [comment]
Here is an update.

I will try to fix the followings.

- [ ] Use GetConcoleCP() instead of CP_ACP.
    - Because I found `chcp` does not change Active Code Page, and do change Console CodePage in spite of displaying `Active code page: xxxx` in console.
- [ ] If GetConsoleCP() is CP_UTF8 which means 65001, use `-u` option automatically and internally.
    - No conversion will be done to output.
- [ ] Fix REPL input logic according to Console Code Page.
    - This is a bug.

Please let me know if you have anything questions.

**Comment by Kray-G** [comment]
Hi @webfolderio,

I did commit some fixes.
Could you check it?
If you need an executable, please let me know.
I will prepare the built one, but I believe you can get it by just doing `git pull` and `make.cmd`.

Thanks in advance.

**Comment by webfolderio** [comment]
This is amazing. It it works perfectly.
Thanks for the quick fix.

<img width="674" alt="repl-console-tr" src="https://user-images.githubusercontent.com/23472649/94521019-fe6cd680-0235-11eb-9ff4-51dd7f3231b8.png">

**Comment by Kray-G** [comment]
Very good.
Thanks for your conformation.
